"""add_customers_table

Revision ID: f00a24e0de95
Revises: bc0de0d0764b
Create Date: 2025-03-21 13:12:43.597910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00a24e0de95'
down_revision = 'bc0de0d0764b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('full_name', sa.String(), nullable=False))
    op.drop_column('customers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('customers', 'full_name')
    # ### end Alembic commands ### 